# Generated by Django 5.0.14 on 2025-09-08 12:39

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags_alter_post_publish'),
    ]

    operations = [
        TrigramExtension()
    ]
